### ISSUE TITLE
USER STORY : Allow Customers to Add Menu Items to Order

### ISSUE THREAD

**Issue by MFS4711** [MFS4711/capstone-prereq#13]
As a **customer**, I can **select menu items and add them to my order**, so that I can **place an order.**

## Acceptance Criteria
* Customers can view the menu and select items to add to their order.
* Customers can add multiple items to their order.

## Tasks
- [ ] Create an Order model that will hold a reference to the Customer and the MenuItem.
- [ ] Create a OrderItem model that links to MenuItem and Order with fields for quantity and status.
- [ ] Create an add_to_order() view that adds items to an order.
- [ ] Display a simple cart UI to show added items.
- [ ] Use JavaScript to update the cart dynamically when items are added or removed.
- [ ] Test adding items to the order and ensure data is correctly saved in the database.
