### ISSUE TITLE
USER STORY : Allow Customers to Modify Their Orders

### ISSUE THREAD

**Issue by MFS4711** [MFS4711/capstone-prereq#14]
As a **role**, I can **capability**, so that I can **benefit**

## Acceptance Criteria
* Customers can increase or decrease item quantities.
* Customers can remove items from the order.
* Modifications should reflect immediately in the database.

## Tasks
- [ ] Add functionality to update the quantity of items in an order.
- [ ] Add functionality to remove items from an order.
- [ ] Create a view that updates the OrderItem status when items are modified.
- [ ] Ensure changes are reflected in the cart and the database.
- [ ] Implement confirmation dialogs for item removal or modification to prevent accidental changes.
- [ ] Test modifications to the order to ensure they are saved correctly.
