### ISSUE TITLE
USER STORY : Set up Django Allauth for User Registration and Login

### ISSUE THREAD

**Issue by MFS4711** [MFS4711/capstone-prereq#2]
As a **user**, I can **register and log in**, so that I can **access my personal account.**

## Acceptance Criteria
* Users can register via email and password.
* Users can log in/log out successfully.
* Include account management features (password reset, etc.).

## Tasks
- [ ] Install Django Allauth and configure it in the INSTALLED_APPS and urls.py.
- [ ] Set up Django Allauth templates for registration and login forms.
- [ ] Configure user authentication views and URLs for registration, login, and logout.
- [ ] Test the registration and login functionality to ensure it's working.
- [ ] Implement password reset functionality using Django Allauth.
- [ ] Test the password reset functionality and ensure it sends emails correctly.
- [ ] Add django-allauth email verification feature and test it.
