### ISSUE TITLE
USER STORY : Allow Staff to Mark Menu Items as Out of Stock

### ISSUE THREAD

**Issue by MFS4711** [MFS4711/capstone-prereq#20]
As a **staff member**, I can **mark items as out of stock**, so that **customers cannot order them until they're available again.**

## Acceptance Criteria
* Staff can mark any menu item as out of stock.
* Out of stock items are visually displayed as unavailable on the menu.

## Tasks
- [ ] Add an available or out_of_stock boolean field to the MenuItem model.
- [ ] Create an admin interface to update the availability of menu items.
- [ ] Display the out-of-stock items differently (e.g., greyed out, with a "Sold Out" tag).
- [ ] Test the functionality of marking items as out of stock and ensuring they are displayed correctly in the menu.
