### ISSUE TITLE
USER STORY : Allow Customers to Add Special Instructions

### ISSUE THREAD

**Issue by MFS4711** [MFS4711/capstone-prereq#23]
As a **customer**, I can **add special instructions (e.g., "no onions", "extra spicy") to my order**, so that I can **customize my meal.**

## Acceptance Criteria
* Customers can enter special instructions on the order page.
* Instructions are displayed with the order in the staff management view.

## Tasks
- [ ] Add a special_instructions field to the OrderItem model.
- [ ] Update the order form to allow customers to input special instructions.
- [ ] Display these instructions to the staff on their interface.
- [ ] Test that special instructions are saved correctly in the database and displayed properly.
