### ISSUE TITLE
USER STORY : Allow Staff to Leave Internal Notes on Orders

### ISSUE THREAD

**Issue by MFS4711** [MFS4711/capstone-prereq#24]
As a **staff member**, I can **add internal notes to orders**, so that I can **team members can communicate details about the order (e.g., "customer requested no ice").**

## Acceptance Criteria
* Staff can add notes to orders in the order management view.
* Notes are visible to staff but not to customers.

## Tasks
- [ ] Add an internal_notes field to the Order model.
- [ ] Create a simple text area for staff to add notes to the order in the staff interface.
- [ ] Ensure that notes are only visible to staff in the backend.
- [ ] Test that notes are properly stored and visible to staff.
